language: node_js
node_js: node
services:
  -mongodb
deploy:
  provider: heroku
  api_key:
    secure: WJB1IUfXDVYaSSKVFKSQGW4UBbLJ9uC+bcu2DKaHyAS1Lj+oDALaKH3b+hkjz+tj1yVylHU8DRk7YzrgxtOUZBDFbIM8dOyZhZUIexIa6Blth/LWDA5QRLVT44j33poXdWMnW0f275V4BwFY9qLFFw1qLods0VKD865ZgkncrCeYuTSZl7Ki2V/5CTAjJhcN/CKU7KhwvvHOP7CediKkw13Fz10s0OQ3iwwVNEqETfZJQ2Zfaa+rGped0EyivtGd247yOQu0vJdFd6WsN+oZhF72HV5oww8m00Tk885lgFzsn6PeKibR3AMlFY9k15svAWR/g8wZx1TpojKz2OpyrURCIx1dtcRlYnRTenIYQuY7ytOJqmY60S8j5QfQ4pHoVJVckmNSlP+ceXnZXgmmaTutpFTOdA17dufx5FZxwUIUKAZwwqWuBGaXbGZaTOTAkSweZVk0P88JjUqYWyspV08WjQKcd1shGGsijSW0JJGsdsdpjopQ8w+AFi+TRwi4f1ldImpugYTwt8ufnUn/fKMVn2aVh4Jsym7mxzq7j8yuh95spF/qyH4y+VlDKYPGxWk7LziveHNk5gMCicmyW1is4wKOBQSRzSp8VWXvRa3u0vgMsU9wv+N8UxONxJ+sXb/zH2H7pvrEntUz7Ac97ej2iETcKP4ZaILMr/rjDps=
  app: cryptic-basin-53606
  on:
    repo: mattpeebles/sscapstone
